apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: {{ include "nginx-gateway.proxy-config-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
spec:
  {{- if .Values.nginx.config }}
  {{- toYaml .Values.nginx.config | nindent 2 }}
  {{- end }}
  kubernetes:
    {{- if eq .Values.nginx.kind "deployment" }}
    deployment:
      {{- if .Values.nginx.replicas }}
      replicas: {{ .Values.nginx.replicas }}
      {{- end }}
      autoscaling:
        enabled: {{ .Values.nginx.autoscaling.enabled }}
        {{- if .Values.nginx.autoscaling.hpaAnnotations }}
        hpaAnnotations:
          {{- toYaml .Values.nginx.autoscaling.hpaAnnotations | nindent 10 }}
        {{- end }}
        minReplicas: {{ .Values.nginx.autoscaling.minReplicas }}
        maxReplicas: {{ .Values.nginx.autoscaling.maxReplicas }}
        targetCPUUtilizationPercentage: {{ .Values.nginx.autoscaling.targetCPUUtilizationPercentage }}
        targetMemoryUtilizationPercentage: {{ .Values.nginx.autoscaling.targetMemoryUtilizationPercentage }}
        {{- if .Values.nginx.autoscaling.behavior }}
        behavior:
          {{- toYaml .Values.nginx.autoscaling.behavior | nindent 10 }}
        {{- end }}
        {{- if .Values.nginx.autoscalingTemplate }}
        autoscalingTemplate:
          {{- toYaml .Values.nginx.autoscalingTemplate | nindent 8 }}
        {{- end }}
      {{- if .Values.nginx.pod }}
      pod:
        {{- toYaml .Values.nginx.pod | nindent 8 }}
      {{- end }}
      container:
        {{- if .Values.nginx.container }}
          {{- toYaml .Values.nginx.container | nindent 8 }}
        {{- end }}
        image:
          {{- toYaml .Values.nginx.image | nindent 10 }}
        {{- if .Values.nginx.debug }}
        debug: {{ .Values.nginx.debug }}
        {{- end }}
    {{- end }}
    {{- if eq .Values.nginx.kind "daemonSet" }}
    daemonSet:
      {{- if .Values.nginx.pod }}
      pod:
        {{- toYaml .Values.nginx.pod | nindent 8 }}
      {{- end }}
      container:
        {{- if .Values.nginx.container }}
          {{- toYaml .Values.nginx.container | nindent 8 }}
        {{- end }}
        image:
          {{- toYaml .Values.nginx.image | nindent 10 }}
        {{- if .Values.nginx.debug }}
        debug: {{ .Values.nginx.debug }}
        {{- end }}
    {{- end }}
    {{- if .Values.nginx.service }}
    service:
      {{- with .Values.nginx.service }}
      {{- include "filterEmptyFields" . | nindent 6 }}
      {{- end }}
    {{- end }}
